### ISSUE TITLE
replace tests/data/... with json-fg dataset

### ISSUE THREAD

**Issue by Ylannl** [3DGI/jsonfg-viewer#1]

**Comment by balazsdukai** [comment]
Hm, the [3dbag_5907.json](https://github.com/3DGI/jsonfg-viewer/blob/de375871b1ed0f808353bae5b8a54593ec0eb20f/tests/data/3dbag_5907.json) is a json-fg file. Isn't it what you meant?

**Comment by Ylannl** [comment]
oh shoot. I got confused by the `.jsonfg` extension of the sample data at https://data.3dgi.xyz/jsonfg/3dbag/jsonfg/ (I guess it should be changed to `.json`?). False alarm then!

**Comment by balazsdukai** [comment]
I think it is still up for discussion.
I was not consistent in this repo. I used .jsonfg in the converted data to distinguish the files. I'll rename this one to .jsonfg too.

**Comment by Ylannl** [comment]
to be honest `.json` might be better, easier to handle with software that reads json. Also the same as geojson.
