### ISSUE TITLE
Handle more geometry types

### ISSUE THREAD

**Issue by Ylannl** [3DGI/jsonfg-viewer#10]
Decide which ones need to be handled and add them there:
https://github.com/3DGI/jsonfg-viewer/blob/253717ae71086bf0fab52667f3fcc44ba141ee3b/src/jsonfg-threejs-loader/parsers/FeatureParser.js#L87

**Comment by balazsdukai** [comment]
The view extent setting works with (almost) all types.
The geometry parsing and and display works for Polyhedron, MultiPolygon, MultiPolyhedron.
This is enough to handle the 3D BAG and 3D Basisvoorziening data that we converted, plus the data from ldproxy's Montreal api.
Which is pretty much all the available 3D data there is atm, so I'll close this for now.
Implemented in #16
